### ISSUE TITLE
主页展示图片格式（体积）

### ISSUE THREAD

**Issue by skykeyjoker** [peterpei1186861238/A-Soul-Database#11]
在主页展示的图片格式png居多（例如向晚），体积较大，略微影响访问速度。
是否可以考虑讲展示的图片转为jpg格式减小体积以优化访问速度？

**Comment by peterpei1186861238** [comment]
收到，这两天修复

**Comment by peterpei1186861238** [comment]
不过jpg会出现图片透明度丢失,会考虑png体积压缩或者webp格式

**Comment by skykeyjoker** [comment]
> 不过jpg会出现图片透明度丢失,会考虑png体积压缩或者webp格式

可以考虑webp格式捏💕

**Comment by peterpei1186861238** [comment]
已修复
