### ISSUE TITLE
请问数据库是实时更新的吗

### ISSUE THREAD

**Issue by lrq619** [peterpei1186861238/A-Soul-Database#13]
还是需要人工手动更新？

**Comment by peterpei1186861238** [comment]
人工手动的捏

**Comment by lrq619** [comment]
好的，准备帮您重写个前端，顺便部署到服务器上（我有台空闲的），写完了我会提交pr

**Comment by peterpei1186861238** [comment]
感谢,
由于目前项目托管在GitHub pages上
所以你的pr如果也可以直接在GitHub pages上跑的话我会提交进主分支

**Comment by lrq619** [comment]
我快写完了，还剩下一些搜索功能没有实现，目前可以放在github pages上。大概明天就能完成捏。我准备把搜索功能整合在List页面还有字幕库页面中，不会单独放一个搜索页面出来。
https://lrq619.github.io/A-Soul-Database/dist/index.html#/./index

**Comment by peterpei1186861238** [comment]
收到收到收到，感谢捏

**Comment by yoursweetie** [comment]
刚开始还吓一跳这么nb吗，得从b站爬视频，获取清洗数据，最困难的是提取视频里的信息，手动真的辛苦了

**Comment by peterpei1186861238** [comment]
> 
> 
> 刚开始还吓一跳这么nb吗，得从b站爬视频，获取清洗数据，最困难的是提取视频里的信息，手动真的辛苦了

像是背景和服饰，这类确实是必须人工标注，或者训练个cv模型，对于现在补平历史之后其实工作量不大（当然如果有合适的话肯定自动）。这正说明没有人做过，才有意义。

**Comment by usercao** [comment]
> 好的，准备帮您重写个前端，顺便部署到服务器上（我有台空闲的），写完了我会提交pr

写完了吗？

**Comment by peterpei1186861238** [comment]
> 
> 
> > 好的，准备帮您重写个前端，顺便部署到服务器上（我有台空闲的），写完了我会提交pr
> 
> 写完了吗？

[/pull/14](https://github.com/peterpei1186861238/A-Soul-Database/pull/14)

**Comment by lrq619** [comment]
> > 好的，准备帮您重写个前端，顺便部署到服务器上（我有台空闲的），写完了我会提交pr
> 
> 写完了吗？

写完了捏

**Comment by lrq619** [comment]
> > 写完了捏
> 
> 为什么现在404打不开了？

可能正在部署吧，我不道啊

**Comment by peterpei1186861238** [comment]
我超，请先访问
https://www.asdb.live/web/index.html
这cdn我不好说

**Comment by lrq619** [comment]
> 我超，请先访问
> https://www.asdb.live/web/index.html
> 这cdn我不好说

我超，看来果然是封面两个大按钮的超链接不太对，我不如现在就修改一下

**Comment by lrq619** [comment]
现在改好了

**Comment by peterpei1186861238** [comment]
看到了，马上push

**Comment by peterpei1186861238** [comment]
等等，移动端不是响应式的啊。。。肝

**Comment by peterpei1186861238** [comment]
移动端好像不是响应式的啊。。。

**Comment by usercao** [comment]
这是to C的页面，整成管理后台了=  =

**Comment by lrq619** [comment]
> 移动端好像不是响应式的啊。。。

目前不是，不过要加响应式布局也很简单，我可以这几天做

**Comment by lrq619** [comment]
> 这是to C的页面，整成管理后台了= =

antd确实本身是做中后台的，但我觉得数据库嘛，方便检索和查找，做成这种严谨一点的风格也可以。。。不知道你们怎么看了

**Comment by usercao** [comment]
感觉炫酷一点好看点，用户一般就喜欢炫酷的

**Comment by peterpei1186861238** [comment]
先把移动端加上吧，不然手机用不了捏。移动端流量不小，或者我移动端就重定向到老版本了QWQ

**Comment by lrq619** [comment]
> 先把移动端加上吧，不然手机用不了捏。移动端流量不小，或者我移动端就重定向到老版本了QWQ

收到，你现在先定向至老版本吧，我今天内把响应式布局搞定

**Comment by lrq619** [comment]
> 先把移动端加上吧，不然手机用不了捏。移动端流量不小，或者我移动端就重定向到老版本了QWQ

不好意思，今天还没做完。今天主要把时间花在将react源码迁移过来并跑通了，放在/make-front-end里，晚上只做了一个index页面的响应式布局，剩下两个页面我睡醒了起来做就好。

**Comment by lrq619** [comment]
> 先把移动端加上吧，不然手机用不了捏。移动端流量不小，或者我移动端就重定向到老版本了QWQ

响应式布局已完成

**Comment by peterpei1186861238** [comment]
今天部署，不到这cdn啥时候刷新好

**Comment by lrq619** [comment]
> 今天部署，不到这cdn啥时候刷新好

好嘞，我在我自己的服务器上写了个定时脚本，每天凌晨零点10分会自动更新前端
