### ISSUE TITLE
可以指定一下timeline的规范吗？

### ISSUE THREAD

**Issue by zzjjbb** [peterpei1186861238/A-Soul-Database#16]
[某些timeline](https://github.com/peterpei1186861238/A-Soul-Database/blob/69f3cc861ff2cd8a38c1646b860663e62dbfa914/db/2021/05/timeline/BV1xN411f7Qv.txt)的格式太乱，可以指定一个timeline的格式规范吗？这样方便大家加入新的timeline以及相关的后续分析

**Comment by zzjjbb** [comment]
假如可以加入绝对的（不依赖于某人的录播投稿，比如贾布加布）时间戳就更好了。或者加入一个起始的offset信息

**Comment by zzjjbb** [comment]
> 
> 
> 假如可以加入绝对的（不依赖于某人的录播投稿，比如贾布加布）时间戳就更好了。或者加入一个起始的offset信息

不过这玩意可能仅供参考，毕竟不同客户端接收到的flv片段可能也有几秒的延迟误差

**Comment by peterpei1186861238** [comment]
抱歉才看到，是这样的，如您所见，timeline的来源是通过贾布老师的视频上传的，时间轴也是评论中的。
timeline其实已经合并到了tags中，通过 `/tools/process/1tags/autoTag.py` 进行时间轴的 **去除** 并分割添加进tags中去
如果有更好的建议也欢迎 ：）

**Comment by zzjjbb** [comment]
嗯，我明白了，所以这个时间轴目前主要还是用来索引整场录播的关键词。我打算做一个类似是录播的播放器，然后把timeline信息加进去。其他没什么问题，就是格式有点乱。不过改格式应该不麻烦，我可以整理一下
