### ISSUE TITLE
8.25好多小乃琳 活动列表为空

### ISSUE THREAD

**Issue by lrq619** [peterpei1186861238/A-Soul-Database#21]
为啥8.25的直播活动列表是空的捏？这会导致无法搜索到
相似的问题还有8.23测试直播和9.5游戏室，场景为空。

**Comment by peterpei1186861238** [comment]
收到收到，今天会check一下

**Comment by peterpei1186861238** [comment]
除了好多小乃琳，我这里活动列表不是空的qaq
![图片](https://user-images.githubusercontent.com/32994395/132639893-b1d1c35a-d2f7-4f2c-9ec2-e40c6ed9c8f7.png)
![图片](https://user-images.githubusercontent.com/32994395/132639916-28cc88a8-f96f-4fbe-9a94-738db85f3ddc.png)
然后好多小乃琳是因为直播既没有唱歌也没有跳舞，我现在手动加上了️表情包鉴赏这个活动 🧎

**Comment by lrq619** [comment]
<img width="375" alt="60ecc7bb61c72a07afc2cd5a2395e3c" src="https://user-images.githubusercontent.com/58351056/132690775-5ef69c2b-14ce-48c9-8b16-db22e90ff0d9.png">
<img width="386" alt="4ffa569bd06dd7570816a99d2744e6d" src="https://user-images.githubusercontent.com/58351056/132690856-37278341-58bb-4c04-b9fc-0f6161ebbe18.png">
收到，8.25“好多小乃琳”已修复。问题是9.25游戏室和8.23测试直播的“场景”这一栏是空的

**Comment by peterpei1186861238** [comment]
游戏室这个直播是因为这个好像是新场景，我铸币了，看着像是演播室。。不知道你怎么看
![图片](https://user-images.githubusercontent.com/32994395/132715191-e35dbfb3-9adb-441b-9359-ce2f79be5a71.png)


其他场景空的初步排查了，好像是前端代码的问题？
不止这两个，嘉然的50W粉丝直播，`【A-SOUL】嘉然/向晚 7.22 夏日欧皇决定战【直播录像】` 等统统没有场景。
因为这些直播数据都是同时 **涉及多个场景的** ，在json文件种 `scene` 都有 **不止一个条目** 。 初步怀疑是前端json解析问题？

**Comment by lrq619** [comment]
> 游戏室这个直播是因为这个好像是新场景，我铸币了，看着像是演播室。。不知道你怎么看
> ![图片](https://user-images.githubusercontent.com/32994395/132715191-e35dbfb3-9adb-441b-9359-ce2f79be5a71.png)
> 
> 其他场景空的初步排查了，好像是前端代码的问题？
> 不止这两个，`嘉然的50W粉丝直播`，`【A-SOUL】嘉然/向晚 7.22 夏日欧皇决定战【直播录像】` 等统统没有场景。
> 因为这些直播数据都是同时 **涉及多个场景的** ，在json文件种 `scene` 都有 **不止一个条目** 。 初步怀疑是前端json解析问题？

收到，应该是前端解析的问题，我没有考虑过多场景的问题，我以为场景都是单一的。今晚上回去我会看一下

**Comment by peterpei1186861238** [comment]
收到  , 那我初步定为 `boardcastroom` 了。
除此之外咱们网站有没有必要搞几个友链这种。。现在托管在Asf cdn上面有些小伙伴从asf跳转之后返回不了，之前给我反馈过

**Comment by lrq619** [comment]
> 收到 , 那我初步定为 `boardcastroom` 了。
> 除此之外咱们网站有没有必要搞几个友链这种。。现在托管在Asf cdn上面有些小伙伴从asf跳转之后返回不了，之前给我反馈过

深以为然，我准备把网站左上角的图标直接链接回asf，以及把“关于”页面加一些asoul人员的图片，而不是现在干巴巴的文字。将在这个周末内完成（大概吧。。。最近在自学操作系统，时间比较碎片化）

**Comment by peterpei1186861238** [comment]
+1 ,还是生活为主捏

**Comment by lrq619** [comment]
> 收到 , 那我初步定为 `boardcastroom` 了。
> 除此之外咱们网站有没有必要搞几个友链这种。。现在托管在Asf cdn上面有些小伙伴从asf跳转之后返回不了，之前给我反馈过

老哥，这个拼写应该有误，应该是`broadcastroom`吧？我代码还是按照正确拼写`broadcastroom`来建立字典。

**Comment by peterpei1186861238** [comment]
broadcast , 我铸币了 🧎🙇

**Comment by lrq619** [comment]
> 一个想法，不一定对，搜索大小写现在是不是还不能混，刚刚搜rollin发现的

对的，大小写现在还敏感

**Comment by peterpei1186861238** [comment]
然后咱们之前说的 可以通过时间轴跳转那种
`bilibili.com/BVxxxxxxxxx?p=&t=`

**Comment by lrq619** [comment]
> 然后咱们之前说的 可以通过时间轴跳转那种
> `bilibili.com/BVxxxxxxxxx?p=&t=`

ok，今天把大小写，时间轴跳转还有build的问题都试图解决了

**Comment by lrq619** [comment]
> 然后咱们之前说的 可以通过时间轴跳转那种
> `bilibili.com/BVxxxxxxxxx?p=&t=`

大小写现在已经不敏感。字幕库和视频库都加了时间轴跳转功能，目前功能良好
