### ISSUE TITLE
修改搜索算法过程中发现的几个数据库小bug

### ISSUE THREAD

**Issue by lrq619** [peterpei1186861238/A-Soul-Database#22]
`【A-SOUL游戏室】十六期 9.5 嘿呜！吼吼吼吼吼吼吼吼~~~~~` 的场景`scene`应改为:`["broadcastroom"]`,目前值:`["gameroom"]`
`【A-SOUL小剧场】第七期 2.5 一起来过小年夜 !【直播录像】`的平台`platform`应改为:`"B"`,目前值:`""`
`【A-SOUL】贝拉的心跳大挑战 1.28【直播录像】`的平台`platform`应改为:`"B"`,目前值:`""`
以上两个视频都是平台值为空，我不知道这是不是因为这两个视频都是b站抖音双平台的。但就算是双平台，我认为也应该加一个特殊的双平台键值对而非留空。
`【A-SOUL】乃琳 1.16 温柔夜谈【直播录像】`的服饰`skin`应改为:`{"E":["official"]}`,目前值:`{"E":"official"}`(每个人物对应的应该是一个字符串数组而非字符串本身)

**Comment by peterpei1186861238** [comment]
收到

**Comment by peterpei1186861238** [comment]
因为默认主键是Bv，所以即使是抖限，也只是会在platform中记录，而其他信息则是以B站上找的录播为准。

**Comment by peterpei1186861238** [comment]
已修复
