### ISSUE TITLE
srt sources

### ISSUE THREAD

**Issue by akhui** [peterpei1186861238/A-Soul-Database#24]
直播字幕文件是怎么扒下来的呢

**Comment by peterpei1186861238** [comment]
1.剪映语音转字幕 
2.配合工具提取出来 [](https://github.com/ruotianluo/baipiao_jianying)
3.通过简单的特定关键词替换得到 `tools/process/2srt/srtChange.json`

每次更新时会生成 search.json 包含字幕内容。

**Comment by akhui** [comment]
thanks!
