### ISSUE TITLE
新功能：页面内跳转

### ISSUE THREAD

**Issue by lrq619** [peterpei1186861238/A-Soul-Database#25]
搜索字幕库之后，打开对应的搜索结果窗口之后，将页面自动跳转到高亮显示的搜索结果处
这周内完成

**Comment by peterpei1186861238** [comment]
收到，我在想是否还能加入字幕下载链接
请务必在更新时先进行git pull ，thanks 🥰🥰

**Comment by lrq619** [comment]
> 收到，我在想是否还能加入字幕下载链接
> 请务必在更新时先进行git pull ，thanks 🥰🥰

收到，好像上一次忘记pull了，不好意思哈。
字幕下载我个人觉得应用场景不大？下载字幕文件下来有什么用呢。。。我暂时没有想到，做二创真的需要一个字幕文件吗。。。
反倒是我觉得如果未来能加入上传字幕，或者上传打轴是比较好的功能。评论区不是一直有打轴man吗，我记得还有一个做全录播打轴的计划。如果能直接让他们在这个网站上进行打轴，然后结果直接展示出来，会是一个比较不错的。
而且字幕不是机器生成吗，讹误率比较大，如果能加入上传功能，也就意味着用户可以帮我们进行人工修改了（如果有为爱发电的au的话，暂时不用考虑恶意用户？因为我觉得体量不大，进来的应该都是真粉）
当然这意味着要写后端，不过只是一个api的程度我可以做到。
一个提议，不一定对。

**Comment by peterpei1186861238** [comment]
![图片](https://user-images.githubusercontent.com/32994395/133546647-175a87ab-489e-40f4-9a01-3720466d557a.png)
官方的切片也是有字幕的，当然如果不好加的话可以不管
自己上传轴倒是个好想法，要不通过提issue然后人工审核吧，不然乱提交这事搞不好，其次就是开Api的话肯定要服务器了

**Comment by lrq619** [comment]
> ![图片](https://user-images.githubusercontent.com/32994395/133546647-175a87ab-489e-40f4-9a01-3720466d557a.png)
> 官方的切片也是有字幕的，当然如果不好加的话可以不管
> 自己上传轴倒是个好想法，要不通过提issue然后人工审核吧，不然乱提交这事搞不好，其次就是开Api的话肯定要服务器了

提交issue的话。。。很多人不会用github，比如上次我找那个全录播的人合作，他就说他不会用github。
服务器倒是不用担心，我有一台腾讯云的，闲置好久了，不用白不用

**Comment by peterpei1186861238** [comment]
B站开个动态然后评论吧。
隔壁asoulfan的服务器也能用，但是我还是觉得能不用的话尽量不用。

**Comment by lrq619** [comment]
> B站开个动态然后评论吧。
> 隔壁asoulfan的服务器也能用，但是我还是觉得能不用的话尽量不用。

这样也不错，那到时候你来开动态吧。你的号比我热度高得多

**Comment by peterpei1186861238** [comment]
正确的

**Comment by lrq619** [comment]
完成了，虽然不是在这周内完成的，超时一小时，但不管怎么说，主播的承诺一向很实，好吧？
改了下字幕库的页面结构，可能会导致响应式布局出现问题，明早我去调一调，先歇逼了

**Comment by peterpei1186861238** [comment]
注意身体最重要。Btw,之前咱们跳转 是 `?p=&t= ` web可以正常跳转但是手机不行。改为 `?p=&start_progress= ` 即可，**但单位为毫秒**

**Comment by peterpei1186861238** [comment]
不着急捏，慢慢来

**Comment by lrq619** [comment]
> 注意身体最重要。Btw,之前咱们跳转 是 `?p=&t= ` web可以正常跳转但是手机不行。改为 `?p=&start_progress= ` 即可，**但单位为毫秒**

get it

**Comment by lrq619** [comment]
> 注意身体最重要。Btw,之前咱们跳转 是 `?p=&t= ` web可以正常跳转但是手机不行。改为 `?p=&start_progress= ` 即可，**但单位为毫秒**
