### ISSUE TITLE
livedb.asoulfan.com这个域名要快一些修好啊

### ISSUE THREAD

**Issue by lrq619** [peterpei1186861238/A-Soul-Database#26]
livedb.asoulfan.com那个链接要早一些修好啊！挺多人给我说链接点不进去的，这个比较影响使用体验我觉得。很多人也就是好奇点一下，发现点不进去就不会再用了，错过了我们功能强大的数据库，私以为十分可惜😋😋😋

**Comment by peterpei1186861238** [comment]
极度正确的🙇
阿里CDN默认主页有问题 访问 livedb.asoulfan.com/index.html 就行，前天吧好像已经push了go的后端，asoulfan那边运维摆了，我今天看看能不能出个docker image 催一下🙇
