### ISSUE TITLE
字幕对应视频的具体时间 & 增加弹幕

### ISSUE THREAD

**Issue by zhou-zl18** [peterpei1186861238/A-Soul-Database#3]
1.希望字幕搜索结果能同时给出在相应视频里的位置。字幕既然是语音识别的，应该可以对应到录播视频的时间吧？
2.希望增加弹幕及弹幕搜索功能，弹幕数据可以和https://matsuri.icu/ 的作者联系。（matsuri.icu目前只支持单场直播内的弹幕搜索）

**Comment by peterpei1186861238** [comment]
1. 自动识别是使用剪映pc版，软件内显示正常，提取时还没找到具体的时间戳
2. 已经增加过了，直接搜索即可

**Comment by neal2018** [comment]
Hey, 我也很需要字幕的时间戳。

[这个仓库](https://github.com/YDX-2147483647/Jianying-to-srt)似乎能把剪映pc版导出的`draft_content.json`转换成有时间轴的`srt`文件，可以试一下吗？

或者，可以考虑上传原始的json让社区自行处理

感谢
