### ISSUE TITLE
【曲目标注】贝拉 1.21 贝拉突击检查

### ISSUE THREAD

**Issue by AaronFang123** [peterpei1186861238/A-Soul-Database#4]
2-63:39 的标注为 `한 (一)`，实际查证为`クレイジー・ビート`，请核实 🥰

![屏幕截图 2021-08-17 114113](https://user-images.githubusercontent.com/48375763/129661644-76988047-338d-4d3b-b614-9a571f8b14b7.png)

**Comment by peterpei1186861238** [comment]
收到收到收到
