### ISSUE TITLE
访问速度问题

### ISSUE THREAD

**Issue by chasedream1129** [peterpei1186861238/A-Soul-Database#9]
Github Pages+Vercel CDN对国内访问还是相当不友好，是否有想法购置一台服务器？
腾讯云轻量，香港区只需要24元/月还免备案，可以开个爱发电来补贴费用。
或者用Cloudflare的CDN也能一定程度上优化，CF的网络建设还是很好的。

**Comment by peterpei1186861238** [comment]
一开始用的cdn其实就是cf,对我这边网络支持并不是很友好，当然也可以考虑gitee pages加域名反代

**Comment by peterpei1186861238** [comment]
已经在国内cdn了捏：）
